### ISSUE TITLE
Don´t repack the docker-context

### ISSUE THREAD

**Issue by dilgerma** [gesellix-docker/gradle-docker-plugin#24] opened 2015-03-11 05:18 UTC
If the gradle build-directory is part of the docker context and you don´t do gradle clean between builds, the context gets repacked for every build, which might pretty fast lead to Java-Heap Space Exceptions. Maybe it could be worth to investigate if the build of the docker-plugin could ignore its own artifacts (tar.gz in build/tmp)

**Comment by gesellix** [comment] 2015-03-12 22:35
You're right that the plugin currently doesn't handle the gradle build directory in any special way. Your suggestion to recognizing and ignoring former build artifacts isn't so easy to implement, because they're not special to the plugin. Only the build context of the current build is ignored when creating the build context, but that's to not recursively trying to archive itself ;-)

Is it necessary to include the complete gradle build folder as docker build context? As you probably know, the build context is completely sent to the docker daemon and then only the referenced folders and files in the Dockerfile are copied from the tar file to the actual docker image. I would suggest to exclude irrelevant files from the build context by either manually archiving a minimal tar or by using another folder as base for the build context.

The `buildContext` property accepts an InputStream, which might help: when the `buildContext` is configured instead of the `buildContextDirectory`, the plugin won't create a temporary build context (.tgz) but streams the InputStream directly as build request body. There was a bug in former releases, but you might try the current release http://plugins.gradle.org/plugin/de.gesellix.docker/2015-03-07T20-17-57

Another option is the `dockerignore` feature, which currently isn't available in the plugin. Would you guess that such a feature would help for your setup? If so, you could be beta tester ;-)

**Comment by jtgasper3** [comment] 2015-03-25 03:43
I'd beta test the dockerignore feature...

P.S. Great plugin! Thanks for sharing.

**Comment by gesellix** [comment] 2015-03-26 20:33
@jtgasper3 thanks! Do you also have an example project with executable files? This is one feature, the Gradle Tar task doesn't seem to support and which I'll have to compensate.

**Comment by gesellix** [comment] 2015-03-26 21:29
@jtgasper3 I've opened a dedicated issue for the .dockerignore feature, please follow the issue item at #25.

**Comment by gesellix** [comment] 2015-04-09 07:16
@dilgerma could you try to reproduce the issue using the current release? The build context should now automatically be excluded from your builds and the `.dockerignore` feature has been added for additional excludes.

**Comment by gesellix** [comment] 2015-04-26 14:56
@dilgerma closing for now, if you still experience issues when creating the build context, please re-open this issue or create a new one. Thanks!

**Closed by gesellix** 2015-04-26 14:56 UTC
